### ISSUE TITLE
Publically accessible constructor or accessor for `S` to get the SPIR-V bytecode

### ISSUE THREAD

**Issue by mrehayden1** [YoshikuniJujo/language-spir-v#2]
My use case for using bindings to `shaderc` (such as the ones in [shaderc](https://hackage.haskell.org/package/shaderc)) is to compile GLSL at runtime.

However, `S`, the output of `compile`, is an opaque type and has no accessor to the `ByteString`  inside.

Would you accept a patch for this usage?

**Comment by YoshikuniJujo** [comment]
Thank you for using my packages.

Please try to use Language.SpirV.Internal.S (https://hackage.haskell.org/package/language-spir-v-0.1.0.1/docs/Language-SpirV-Internal.html#t:S).

If that doesn't solve it, please contact me.

**Comment by mrehayden1** [comment]
Sorry I missed that `Language.SpirV.Internal` was an exposed module while I'm used to modules named 'Internal' being hidden.

Hopefully there are no plans to make it hidden.
